#!/bin/sh /etc/rc.common

USE_PROCD=1
START=96

start_service() {
    /usr/sbin/haproxy-gen
}

reload_config() {
    /usr/sbin/haproxy-gen
}

service_triggers() {
    procd_add_reload_trigger "haproxy"
}
